collection_name: test_docs_v4
persist_directory: chroma_db
k: 3
data_path: ./data
md5_hex_store: ../rag/md5.text
allow_knowledge_file_type: ["txt", "pdf"]
host: localhost
port: 8000
chunk_size: 300
chunk_overlap: 80
separators: ["\n\n", "\n", ".", "!", "?", "。", "！", "？", " ", ""]
